=== softelnet/sponge/sponge-api/src/main/resources/org/openksavi/sponge/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://sponge.openksavi.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://sponge.openksavi.org"
    elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation>
            <![CDATA[
                Sponge XML configuration schema. For documentation see the main project page https://sponge.openksavi.org.
            ]]>
        </xs:documentation>
    </xs:annotation>

    <xs:element name="sponge" type="Sponge"/>

    <xs:complexType name="Sponge">
        <xs:sequence>
            <xs:element name="properties" type="Properties" minOccurs="0"/>
            <xs:element name="engine" type="Engine" minOccurs="0"/>
            <xs:element name="knowledgeBases" type="KnowledgeBases" minOccurs="0"/>
            <xs:element name="plugins" type="Plugins" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Properties">
        <xs:sequence>
            <xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Property" mixed="true">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="variable" type="xs:boolean" />
        <xs:attribute name="system" type="xs:boolean" />
    </xs:complexType>

    <xs:simpleType name="EventClonePolicy" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="shallow" />
            <xs:enumeration value="deep" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Engine">
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="license" type="xs:string" minOccurs="0" />
            <xs:element name="mainProcessingUnitThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="asyncEventSetProcessorExecutorThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="eventSetProcessorDefaultSynchronous" type="xs:string" minOccurs="0" />
            <xs:element name="eventQueueCapacity" type="xs:string" minOccurs="0" />
            <xs:element name="eventClonePolicy" type="EventClonePolicy" minOccurs="0" />
            <xs:element name="autoEnable" type="xs:string" minOccurs="0" />
            <xs:element name="durationThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="executorShutdownTimeout" type="xs:string" minOccurs="0" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="optional" />
        <xs:attribute name="label" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="KnowledgeBases">
        <xs:sequence>
            <xs:element name="knowledgeBase" type="KnowledgeBase" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KnowledgeBase">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="file" type="KnowledgeBaseFile" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="type" type="xs:string" use="optional" />
        <xs:attribute name="class" type="xs:string" use="optional" />
        <xs:attribute name="clearOnReload" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:complexType name="KnowledgeBaseFile" mixed="true">
        <xs:attribute name="charset" type="xs:string" use="optional" />
        <xs:attribute name="required" type="xs:string" use="optional" default="true" />
    </xs:complexType>

    <xs:complexType name="Plugins">
        <xs:sequence>
            <xs:element name="plugin" type="Plugin" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Plugin">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="configuration" type="PluginConfiguration" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="class" type="xs:string" use="required" />
        <xs:attribute name="knowledgeBaseName" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="PluginConfiguration">
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== softelnet/sponge/sponge-standalone/examples/standalone/news/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="http://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sponge.openksavi.org http://sponge.openksavi.org/schema/config.xsd">

    <properties>
        <!-- News that have less words in the title than specified by this parameter will be rejected by filters. -->
        <property name="newsFilterWordThreshold" variable="true">3</property>
        <!-- Max size of a buffer that stores latest news. -->
        <property name="latestNewsMaxSize" variable="true">5</property>
        <!-- Knowledge base files directory. -->
        <property name="kbDir">examples/standalone/news/kb</property>
    </properties>

    <knowledgeBases>
        <!-- Main knowledge base (implemented in Python) that uses 3 files. These files will be loaded by the same interpreter. -->
        <knowledgeBase name="main">
            <!-- Plugin implemented in Python. -->
            <file>${kbDir}/main_plugins.py</file>
            <!-- Main event processors. For the sake of clarity registration of event processors is placed in the next file. -->
            <file>${kbDir}/main_event_processors.py</file>
            <!-- Knowledge base callback functions: onInit, onLoad, etc. -->
            <file>${kbDir}/main_functions.py</file>
        </knowledgeBase>
        <!-- Actions knowledge base (implemented in JavaScript). -->
        <knowledgeBase name="actions">
            <file>${kbDir}/actions.js</file>
        </knowledgeBase>
        <!-- News generator knowledge base. -->
        <knowledgeBase name="newsGenerator">
            <file>${kbDir}/news_generator.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <!-- Plugin defined in Python. Stores the last news entry". -->
        <plugin name="storagePlugin" class="StoragePlugin" knowledgeBaseName="main">
            <configuration>
                <storedValue>no news yet</storedValue>
            </configuration>
        </plugin>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-examples-projects/sponge-examples-project-demo-service/sponge/sponge.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">

    <properties>
        <!-- Set these properties via system properties in a servlet container environment! -->
        <!-- <property name="digits.home">digits</property> -->
        <!-- <property name="password.file">password.txt</property> -->

        <!-- The optional prediction probability threshold. -->
        <property name="predictionThreshold" variable="true">0.6</property>

        <property name="doodlesDir">${sponge.home}/data/doodles</property>
    </properties>

    <knowledgeBases>
        <knowledgeBase name="demo" label="Demo">
            <file>sponge_demo.py</file>
            <file>sponge_demo_choose_color.py</file>
            <file>sponge_demo_depending.py</file>
            <file>sponge_demo_binary_result.py</file>
            <file>sponge_demo_context_actions_action.py</file>
            <file>sponge_demo_context_actions_record.py</file>
        </knowledgeBase>
        <knowledgeBase name="demoForms" label="Action forms/Base">
            <file>sponge_demo_forms_base.py</file>
        </knowledgeBase>
        <knowledgeBase name="demoFormsLibraryArgs" label="Action forms/Library args">
            <file>sponge_demo_forms_library_common.py</file>
            <file>sponge_demo_forms_library_args.py</file>
        </knowledgeBase>
        <knowledgeBase name="demoFormsLibraryRecord" label="Action forms/Library records">
            <file>sponge_demo_forms_library_common.py</file>
            <file>sponge_demo_forms_library_records.py</file>
        </knowledgeBase>
        <knowledgeBase name="demoPlus" label="Demo plus">
            <file>sponge_demo_doodles.py</file>
        </knowledgeBase>
        <knowledgeBase name="digits" label="Digits">
            <file>${digits.home}/actions/digits_common.py</file>
            <file>${digits.home}/actions/digits_predict.py</file>
            <file>${digits.home}/actions/digits_predict_probabilities.py</file>
            <file>sponge_demo_digits.py</file>
        </knowledgeBase>
        <knowledgeBase name="digitsLearn" label="Digits learn">
            <file>${digits.home}/actions/digits_common.py</file>
            <file>${digits.home}/actions/digits_learn.py</file>
        </knowledgeBase>
        <knowledgeBase name="events" label="Events">
            <file>sponge_demo_events.py</file>
        </knowledgeBase>
        <knowledgeBase name="eventsNotification" label="Notification">
            <file>sponge_demo_events_notification.py</file>
        </knowledgeBase>
        <knowledgeBase name="eventsMemo" label="Memo">
            <file>sponge_demo_events_memo.py</file>
        </knowledgeBase>
        <knowledgeBase name="eventsCounter" label="Counter">
            <file>sponge_demo_events_counter.py</file>
        </knowledgeBase>
        <knowledgeBase name="engine" label="Engine">
            <file>classpath*:org/openksavi/sponge/restapi/server/engine_public_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="admin" label="Admin">
            <file>classpath*:org/openksavi/sponge/restapi/server/engine_admin_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="security" label="Security">
            <file>rest_api_security.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <plugin name="py4j" class="org.openksavi.sponge.py4j.ClientServerPy4JPlugin">
            <configuration>
                <facadeInterface>org.openksavi.sponge.tensorflow.ImageClassifierService</facadeInterface>
                <pythonScript>
                    <executable>${user.home}/tensorflow/bin/python3</executable>
                    <argument>digits_service.py</argument>
                    <!-- The model file and the temporary directory are specified relative to the Python workingDir. -->
                    <argument>--modelfile=../data/digits_model.h5</argument>
                    <argument>--workspacedir=../_workspace_</argument>
                    <workingDir>${digits.home}/python</workingDir>
                    <waitForPositiveLineRegexp>The service has started.</waitForPositiveLineRegexp>
                    <waitForNegativeLineRegexp>The service has failed to start.</waitForNegativeLineRegexp>
                    <outputRedirect>CONSUMER</outputRedirect>
                    <errorRedirect>CONSUMER</errorRedirect>
                </pythonScript>
            </configuration>
        </plugin>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-standalone/examples/standalone/camel_rss_news/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="http://www.openksavi.org/sponge" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openksavi.org/sponge http://www.openksavi.org/sponge/schema/config.xsd">

    <properties>
        <!-- News that have less words in the title than specified by this parameter will be rejected by filters. -->
        <property name="newsFilterWordThreshold" variable="true">3</property>
        <!-- Max size of a buffer that stores latest news. -->
        <property name="latestNewsMaxSize" variable="true">5</property>
        <!-- RSS endpoint URI parameters. -->
        <property name="rssEndpointParameters" variable="true">?sortEntries=false&amp;consumer.delay=1000</property>
        <!-- Duration of reading RSS feeds from sources (in seconds). -->
        <property name="durationOfReadingRss" variable="true">5</property>
        <!-- Base directory. -->
        <property name="baseDir">examples/standalone/camel_rss_news</property>
    </properties>

    <knowledgeBases>
        <knowledgeBase name="config" type="python">
            <!-- Extended configuration (more complex data structures than in properties section). -->
            <file>${baseDir}/kb/config.py</file>
        </knowledgeBase>
        <!-- Main knowledge base (implemented in Python) that uses 3 files. These files will be loaded by the same interpreter. -->
        <knowledgeBase name="main" type="python">
            <!-- Plugin implemented in Python. -->
            <file>${baseDir}/kb/main_plugins.py</file>
            <!-- Main event processors. For the sake of clarity registration of event processors is placed in the next file. -->
            <file>${baseDir}/kb/main_event_processors.py</file>
            <!-- Knowledge base callback functions: onInit, onLoad, onStartup, etc. -->
            <file>${baseDir}/kb/main_functions.py</file>
        </knowledgeBase>
        <!-- Actions knowledge base (implemented in JavaScript). -->
        <knowledgeBase name="actions" type="javascript">
            <file>${baseDir}/kb/actions.js</file>
        </knowledgeBase>
        <!-- A knowledge base that simulates lack of new news after a specified time by stopping corresponding Camel routes. -->
        <knowledgeBase name="simulator" type="python">
            <file>${baseDir}/kb/simulator.py</file>
        </knowledgeBase>
        <!-- As a consumer in Camel routes. -->
        <knowledgeBase name="consumer" type="python">
            <file>${baseDir}/kb/consumer.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <!-- Plugin defined in Python. Stores the last news entry. -->
        <plugin name="storagePlugin" class="StoragePlugin" knowledgeBaseName="main">
            <configuration>
                <storedValue>no news yet</storedValue>
            </configuration>
        </plugin>
        <!-- Standalone plugin that configures Spring and Camel. -->
        <plugin name="standalonePlugin" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring engineBeanName="camelRssEngine" camel="true">
                    <file>${baseDir}/config/CamelRoutes.groovy</file>
                    <file>${baseDir}/config/CamelService.groovy</file>
                </spring>
            </configuration>
        </plugin>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-examples-projects/sponge-examples-project-iot-rpi/kb/sponge_iot.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">

    <properties>
        <property name="password.file">${sponge.configDir}/password.txt</property>
        <property name="camera.dir">${sponge.home}/data/camera</property>
        <property name="pictureFormat" variable="true">jpg</property>
    </properties>

    <knowledgeBases>
        <knowledgeBase name="grovepi" label="Grove Pi">
            <file>sponge_iot_grovepi_device.py</file>
            <file>sponge_iot_grovepi.py</file>
            <file>sponge_iot_grovepi_manage_lcd.py</file>
            <file>sponge_iot_grovepi_manage_sensors.py</file>
            <file>sponge_iot_grovepi_listeners.py</file>
            <file>sponge_iot_grovepi_light.py</file>
        </knowledgeBase>
        <knowledgeBase name="email" label="Email">
            <file>sponge_iot_email.py</file>
        </knowledgeBase>
        <knowledgeBase name="sms" label="SMS">
            <file>sponge_iot_sms.py</file>
            <file>sponge_iot_sms_notification.py</file>
        </knowledgeBase>
        <knowledgeBase name="camera" label="Camera">
            <file>sponge_iot_camera.py</file>
        </knowledgeBase>
        <knowledgeBase name="iot" label="IoT">
            <file>sponge_iot.py</file>
            <file>classpath*:org/openksavi/sponge/restapi/server/engine_public_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="os" label="OS">
            <file>sponge_iot_os.py</file>
        </knowledgeBase>
        <knowledgeBase name="events" label="Events">
            <file>sponge_iot_grpc.py</file>
        </knowledgeBase>
        <knowledgeBase name="admin" label="Admin">
            <file>classpath*:org/openksavi/sponge/restapi/server/engine_admin_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="security" label="Security">
            <file>rest_api_security.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <plugin name="standalone" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true" />
            </configuration>
        </plugin>

        <plugin name="grovepi" class="org.openksavi.sponge.rpi.grovepi.GrovePiPlugin" />

        <plugin name="gsm" class="org.openksavi.sponge.gsmmodem.GammuGsmModemPlugin" />

        <plugin name="restApiServer" class="org.openksavi.sponge.restapi.server.RestApiServerPlugin">
            <configuration>
                <autoStart>false</autoStart>
                <allowAnonymous>false</allowAnonymous>
                <securityServiceClass>org.openksavi.sponge.restapi.server.security.SimpleInMemorySecurityService</securityServiceClass>
            </configuration>
        </plugin>
        <plugin name="grpcApiServer" class="org.openksavi.sponge.grpcapi.server.GrpcApiServerPlugin">
            <configuration>
                <autoStart>false</autoStart>
            </configuration>
        </plugin>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-examples-projects/sponge-examples-project-mpd-mpc/kb/mpd_mpc.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">

    <properties>
        <property name="password.file">${sponge.configDir}/password.txt</property>
    </properties>

    <knowledgeBases>
        <knowledgeBase name="mpd" label="MPD">
            <file>mpd_mpc_service.py</file>
            <file>mpd_mpc.py</file>
            <file>mpd_mpc_player.py</file>
            <file>mpd_mpc_playlist.py</file>
            <file>mpd_mpc_library.py</file>
            <file>mpd_lyrics.py</file>
        </knowledgeBase>
        <knowledgeBase name="administration" label="Administration">
            <file>classpath:org/openksavi/sponge/restapi/server/engine_admin_library.py</file>
            <file>classpath:org/openksavi/sponge/restapi/server/engine_public_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="security" label="Security">
            <file>rest_api_security.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <plugin name="standalone" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true" />
            </configuration>
        </plugin>
        <plugin name="restApiServer" class="org.openksavi.sponge.restapi.server.RestApiServerPlugin">
            <configuration>
                <allowAnonymous>true</allowAnonymous>
                <securityServiceClass>org.openksavi.sponge.restapi.server.security.SimpleInMemorySecurityService</securityServiceClass>
            </configuration>
        </plugin>
        <plugin name="grpcApiServer" class="org.openksavi.sponge.grpcapi.server.GrpcApiServerPlugin"/>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-standalone/examples/standalone/camel_template/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">

    <properties>
        <!-- Base directory. -->
        <property name="baseDir" variable="true">examples/standalone/camel_template</property>
        <property name="templateUri" variable="true">file:${baseDir}/template.mustache</property>
    </properties>

    <knowledgeBases>
        <!-- Main knowledge base (implemented in Python). -->
        <knowledgeBase name="main">
            <file>${baseDir}/main.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <!-- Standalone plugin that configures Spring and Camel. -->
        <plugin name="standalonePlugin" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true">
                    <file>${baseDir}/CamelRoutes.groovy</file>
                </spring>
            </configuration>
        </plugin>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-app/sponge-app-mpd-mpc/kb/mpd_mpc.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">
    <properties>
        <property name="password.file">${sponge.configDir}/password.txt</property>
    </properties>

    <engine name="mpd" label="MPD"/>

    <knowledgeBases>
        <knowledgeBase name="mpd" label="MPD">
            <file>classpath*:sponge/mpd-mpc/**/*.py</file>
        </knowledgeBase>
        <knowledgeBase name="administration" label="Administration">
            <file>classpath*:sponge/engine/*.py</file>
        </knowledgeBase>
        <knowledgeBase name="security" label="Security">
            <file>remote_api_security.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <plugin name="standalone" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true" />
            </configuration>
        </plugin>
        <plugin name="remoteApiServer" class="org.openksavi.sponge.remoteapi.server.RemoteApiServerPlugin">
            <configuration>
                <allowAnonymous>true</allowAnonymous>
                <securityProviderClass>org.openksavi.sponge.remoteapi.server.security.SimpleInMemorySecurityProvider</securityProviderClass>
                <registerServiceDiscovery>true</registerServiceDiscovery>
            </configuration>
        </plugin>
        <plugin name="grpcApiServer" class="org.openksavi.sponge.grpcapi.server.GrpcApiServerPlugin"/>
    </plugins>
</sponge>

=== softelnet/sponge/sponge-examples-projects/sponge-examples-project-spring-boot/config/sponge.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">
    <knowledgeBases>
        <knowledgeBase name="python">
            <file>${sponge.home}/sponge/sponge.py</file>
            <file>${sponge.home}/sponge/employees.py</file>
        </knowledgeBase>
        <knowledgeBase name="admin" label="Admin">
            <file>classpath:sponge/engine/engine_admin_library.py</file>
            <file>classpath:sponge/engine/engine_public_library.py</file>
        </knowledgeBase>
        <knowledgeBase name="security">
            <file>${sponge.home}/sponge/remote_api_security.py</file>
        </knowledgeBase>
    </knowledgeBases>
</sponge>
