=== softelnet/sponge/sponge-api/src/main/resources/org/openksavi/sponge/schema/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="https://sponge.openksavi.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://sponge.openksavi.org"
    elementFormDefault="qualified">
    <xs:annotation>
        <xs:documentation>
            <![CDATA[
                Sponge XML configuration schema. For documentation see the main project page https://sponge.openksavi.org.
            ]]>
        </xs:documentation>
    </xs:annotation>

    <xs:element name="sponge" type="Sponge"/>

    <xs:complexType name="Sponge">
        <xs:sequence>
            <xs:element name="properties" type="Properties" minOccurs="0"/>
            <xs:element name="engine" type="Engine" minOccurs="0"/>
            <xs:element name="knowledgeBases" type="KnowledgeBases" minOccurs="0"/>
            <xs:element name="plugins" type="Plugins" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Properties">
        <xs:sequence>
            <xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Property" mixed="true">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="variable" type="xs:boolean" />
        <xs:attribute name="system" type="xs:boolean" />
    </xs:complexType>

    <xs:simpleType name="EventClonePolicy" final="restriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="shallow" />
            <xs:enumeration value="deep" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Engine">
        <xs:all>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="license" type="xs:string" minOccurs="0" />
            <xs:element name="mainProcessingUnitThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="asyncEventSetProcessorExecutorThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="eventSetProcessorDefaultSynchronous" type="xs:string" minOccurs="0" />
            <xs:element name="eventQueueCapacity" type="xs:string" minOccurs="0" />
            <xs:element name="eventClonePolicy" type="EventClonePolicy" minOccurs="0" />
            <xs:element name="autoEnable" type="xs:string" minOccurs="0" />
            <xs:element name="durationThreadCount" type="xs:string" minOccurs="0" />
            <xs:element name="executorShutdownTimeout" type="xs:string" minOccurs="0" />
        </xs:all>
        <xs:attribute name="name" type="xs:string" use="optional" />
        <xs:attribute name="label" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="KnowledgeBases">
        <xs:sequence>
            <xs:element name="knowledgeBase" type="KnowledgeBase" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KnowledgeBase">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="file" type="KnowledgeBaseFile" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="type" type="xs:string" use="optional" />
        <xs:attribute name="class" type="xs:string" use="optional" />
        <xs:attribute name="clearOnReload" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>

    <xs:complexType name="KnowledgeBaseFile" mixed="true">
        <xs:attribute name="charset" type="xs:string" use="optional" />
        <xs:attribute name="required" type="xs:string" use="optional" default="true" />
    </xs:complexType>

    <xs:complexType name="Plugins">
        <xs:sequence>
            <xs:element name="plugin" type="Plugin" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Plugin">
        <xs:sequence>
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="configuration" type="PluginConfiguration" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="label" type="xs:string" use="optional" />
        <xs:attribute name="class" type="xs:string" use="required" />
        <xs:attribute name="knowledgeBaseName" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="PluginConfiguration">
        <xs:sequence>
            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== softelnet/sponge/sponge-standalone-app/services/remote/remote.xml
<?xml version="1.0" encoding="UTF-8"?>
<sponge xmlns="https://sponge.openksavi.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://sponge.openksavi.org https://sponge.openksavi.org/schema/config.xsd">
    <properties>
        <property name="sponge.serviceDir">${sponge.configDir}/service</property>
        <property name="sponge.workDir">./_work</property>
        <property name="sponge.securityDir">${sponge.configDir}/security</property>

        <property name="password.file">${sponge.configDir}/password.txt</property>
    </properties>

    <engine name="remote" label="Remote"/>

    <knowledgeBases>
        <knowledgeBase name="servicePython" label="Service Python">
            <file required="false">file:${sponge.serviceDir}/**/*.py</file>
            <file required="false">file:${sponge.workDir}/_local_git_cached/kb/**/*.py</file>
        </knowledgeBase>
        <knowledgeBase name="serviceGroovy" label="Service Groovy">
            <file required="false">file:${sponge.serviceDir}/**/*.groovy</file>
            <file required="false">file:${sponge.workDir}/_local_git_cached/kb/**/*.groovy</file>
        </knowledgeBase>
        <knowledgeBase name="serviceRuby" label="Service Ruby">
            <file required="false">file:${sponge.serviceDir}/**/*.rb</file>
            <file required="false">file:${sponge.workDir}/_local_git_cached/kb/**/*.rb</file>
        </knowledgeBase>
        <knowledgeBase name="serviceJavaScript" label="Service JavaScript">
            <file required="false">file:${sponge.serviceDir}/**/*.js</file>
            <file required="false">file:${sponge.workDir}/_local_git_cached/kb/**/*.js</file>
        </knowledgeBase>

        <knowledgeBase name="configuration" label="Configuration">
            <file required="false">${sponge.configDir}/configuration.py</file>
        </knowledgeBase>
        <knowledgeBase name="administration" label="Administration">
            <file>classpath:sponge/engine/engine_admin_library.py</file>
            <file>classpath:sponge/engine/engine_public_library.py</file>
            <file>classpath:sponge/engine/engine_reload_git.py</file>
        </knowledgeBase>
        <knowledgeBase name="security" label="Security">
            <file>file:${sponge.securityDir}/**/*.py</file>
        </knowledgeBase>
    </knowledgeBases>

    <plugins>
        <plugin name="standalone" class="org.openksavi.sponge.standalone.StandalonePlugin">
            <configuration>
                <spring camel="true" />
            </configuration>
        </plugin>
        <plugin name="remoteApiServer" class="org.openksavi.sponge.remoteapi.server.RemoteApiServerPlugin">
            <configuration>
                <allowAnonymous>true</allowAnonymous>
                <securityProviderClass>org.openksavi.sponge.remoteapi.server.security.SimpleInMemorySecurityProvider</securityProviderClass>
                <registerServiceDiscovery>true</registerServiceDiscovery>
            </configuration>
        </plugin>
        <plugin name="grpcApiServer" class="org.openksavi.sponge.grpcapi.server.GrpcApiServerPlugin"/>
    </plugins>
</sponge>
